// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnSI8demiU8BwH6Aeobkaz0xtvKa2XCgc',
    appId: '1:83636808572:web:570f17edc44298072892f9',
    messagingSenderId: '83636808572',
    projectId: 'consequent-caa63',
    authDomain: 'consequent-caa63.firebaseapp.com',
    storageBucket: 'consequent-caa63.appspot.com',
    measurementId: 'G-JN4WWV73N1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWE-Q5Aj7qDK2KP_SxyxbP834zBKGwOkc',
    appId: '1:83636808572:android:1ab467314a0ed2862892f9',
    messagingSenderId: '83636808572',
    projectId: 'consequent-caa63',
    storageBucket: 'consequent-caa63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcIrNKQ8igomdouAeK5ZwOq-D9lnKc_Wc',
    appId: '1:83636808572:ios:e33564b90dd097932892f9',
    messagingSenderId: '83636808572',
    projectId: 'consequent-caa63',
    storageBucket: 'consequent-caa63.appspot.com',
    iosClientId: '83636808572-9ilhmjttqh50r607hp5v968vmeg6aihe.apps.googleusercontent.com',
    iosBundleId: 'com.example.consequentClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcIrNKQ8igomdouAeK5ZwOq-D9lnKc_Wc',
    appId: '1:83636808572:ios:e33564b90dd097932892f9',
    messagingSenderId: '83636808572',
    projectId: 'consequent-caa63',
    storageBucket: 'consequent-caa63.appspot.com',
    iosClientId: '83636808572-9ilhmjttqh50r607hp5v968vmeg6aihe.apps.googleusercontent.com',
    iosBundleId: 'com.example.consequentClient',
  );
}
